/*
 CASE 1 
	원복 : 파티션 테이블, PK 파티션 
	PARTITION_TABLE
	대상 : 테이블, PK GLOBAL

	-- 대상 테이블이 분리되어질 파티션 번호와 같은 파일 그룹에 존재해야함

*/


DROP TABLE PARTITION_TABLE2

CREATE TABLE PARTITION_TABLE2
	( SEQNO  INT NOT NULL ,
	  NAME	 NVARCHAR(10) NOT NULL
    ) ON PS__PARTITION_TABLE2_SEQNO (SEQNO)

ALTER TABLE PARTITION_TABLE2  ADD CONSTRAINT PK__PARTITION_TABLE2__SEQNO
	PRIMARY KEY CLUSTERED (SEQNO) ON  PS__PARTITION_TABLE2_SEQNO (SEQNO)
GO


DECLARE @i int
SET @i = 1
WHILE (@i < = 90)
BEGIN
	INSERT PARTITION_TABLE2 (seqno, name)
	VALUES (@i, 'test' + convert(nvarchar,@i))
	SET @i = @i + 1
END



-- 파티션 switch
ALTER DATABASE TESTDB ADD FILEGROUP T_PARTITION_FG_04 
go

ALTER DATABASE TESTDB ADD FILE
(	NAME = 'T_PARTITION_FG_04_01',
	FILENAME = 'G:\SQLDATA\T_PARTITION_FG_04_01.NDF',
	SIZE = 5MB,
	FILEGROWTH = 5MB) TO FILEGROUP T_PARTITION_FG_04
go


sp_helpfile
go

-- 테이블을 SWITCH 할꺼랑 같은걸 만든다. 
-- 비어 있어야 한다.
DROP TABLE PARTITION_TABLE_SWITCH

CREATE TABLE PARTITION_TABLE_SWITCH
	( SEQNO  INT NOT NULL ,
	  NAME	 NVARCHAR(10) NOT NULL
    ) ON T_PARTITION_FG_04

ALTER TABLE PARTITION_TABLE_SWITCH  ADD CONSTRAINT PK__PARTITION_TABLE_SWITCH__SEQNO
	PRIMARY KEY CLUSTERED (SEQNO) ON T_PARTITION_FG_04
go

DBCC SHOWFILESTATS
GO

-- 파일 그룹 2번을 SWITCH
ALTER TABLE PARTITION_TABLE2 SWITCH PARTITION 2 TO PARTITION_TABLE_SWITCH ;
GO
 
--메시지 4939, 수준 16, 상태 1, 줄 2
--ALTER TABLE SWITCH 문이 실패했습니다. 인덱스 'TestDB.dbo.PARTITION_TABLE_SWITCH.PK__PARTITION_TABLE_SWITCH__SEQNO'은(는) 파일 그룹 'T_PARTITION_FG_04'에 있고 인덱스 'TestDB.dbo.PARTITION_TABLE2.PK__PARTITION_TABLE2__SEQNO'의 파티션 2은(는) 파일 그룹 'T_PARTITION_FG_02'에 있습니다.

-- 결론) 옮기려는 빈 테이블이 같은 파일 그룹에 있어야 한다.


-- 다시 시도 
DROP TABLE PARTITION_TABLE_SWITCH
GO

CREATE TABLE PARTITION_TABLE_SWITCH
	( SEQNO  INT NOT NULL ,
	  NAME	 NVARCHAR(10) NOT NULL
    ) ON T_PARTITION_FG_02

ALTER TABLE PARTITION_TABLE_SWITCH  ADD CONSTRAINT PK__PARTITION_TABLE_SWITCH__SEQNO
	PRIMARY KEY CLUSTERED (SEQNO) ON T_PARTITION_FG_02
go

-- 파일 그룹 2번을 SWITCH
ALTER TABLE PARTITION_TABLE2 SWITCH PARTITION 2 TO PARTITION_TABLE_SWITCH ;
GO
-- 완료

exec up_DBA_helptable_partition 'PARTITION_TABLE2'

--RIGHT	NULL	1	T_PARTITION_FG_01	0
--RIGHT	10 이상 ~ 20 미만	3	T_PARTITION_FG_03	10 --> 없어짐
--RIGHT	20 이상 ~ 30 미만	4	T_PARTITION_FG_01	10
--RIGHT	30 이상 ~ 50 미만	5	T_PARTITION_FG_02	20
--RIGHT	50 이상 ~ 60 미만	6	T_PARTITION_FG_02	10
--RIGHT	60 이상	7	T_PARTITION_FG_02	31
--RIGHT	10 이상 ~ 10 미만	2	T_PARTITION_FG_02	0
-- 

SELECT * FROM PARTITION_TABLE WHERE SEQNO < 10


SELECT *
FROM SYS.PARTITION_RANGE_VALUES
WHERE  FUNCTION_ID IN
     (
     SELECT FUNCTION_ID
     FROM SYS.PARTITION_FUNCTIONS
     WHERE NAME = ('PF__PARTITION_TABLE_SEQNO')
     )

-- 옮겨간 테이블에 결과 값이 나온다.
SELECT * FROM PARTITION_TABLE_SWITCH
go




--  다음 파일 그룹 파일 그룹 3번을 SWITCH
ALTER TABLE PARTITION_TABLE2 SWITCH PARTITION 3 TO PARTITION_TABLE_SWITCH ;
GO
--메시지 4905, 수준 16, 상태 1, 줄 2
--ALTER TABLE SWITCH 문이 실패했습니다. 대상 테이블 'TestDB.dbo.PARTITION_TABLE_SWITCH'이(가) 비어 있어야 합니다.

/*
	대상에 있는것을 다시 재 SWITCH 한다.

*/

ALTER TABLE PARTITION_TABLE_SWITCH SWITCH TO PARTITION_TABLE2 PARTITION 2 ;
GO
--메시지 4982, 수준 16, 상태 1, 줄 2
--ALTER TABLE SWITCH 문이 실패했습니다. 원본 테이블 'TestDB.dbo.PARTITION_TABLE_SWITCH'의 CHECK 제약 조건에서 대상 테이블 'TestDB.dbo.PARTITION_TABLE2'의 파티션 2에서 정의한 범위가 허용하지 않는 값을 허용합니다.


SELECT OBJECT_NAME(OBJECT_ID), *
FROM SYS.PARTITIONS
WHERE OBJECT_ID = OBJECT_ID('PARTITION_TABLE')
ORDER BY PARTITION_NUMBER, INDEX_ID;
-- 2번이 비어 있다.  그럼에도 불구하고  펑션 제약 조건이 단일 테이블에는 적용되지 않기 때문에 다시 스위칭 하는것을 허용하지 않는다.


-- 꽁수를 사용한다.
-- 함수 생성
CREATE PARTITION FUNCTION PF__PARTITION_TABLE3_SEQNO(int)
AS RANGE RIGHT
FOR VALUES (
   null, 10, 20, 30, 100)
GO

-- 스키마 생성
CREATE PARTITION SCHEME  PS__PARTITION_TABLE3_SEQNO
AS PARTITION PF__PARTITION_TABLE3_SEQNO
TO 
( T_PARTITION_FG_01, T_PARTITION_FG_02, T_PARTITION_FG_03, 
	T_PARTITION_FG_01, T_PARTITION_FG_02, T_PARTITION_FG_03,T_PARTITION_FG_01)
GO


CREATE TABLE PARTITION_TABLE_SWITCH_RE
	( 
	 SEQNO  INT NOT NULL ,
	  NAME	 NVARCHAR(10) NULL
    ) ON PS__PARTITION_TABLE3_SEQNO(SEQNO)

ALTER TABLE PARTITION_TABLE_SWITCH_RE  ADD CONSTRAINT PK__PARTITION_TABLE_SWITCH_RE__SEQNO
	PRIMARY KEY CLUSTERED (SEQNO) ON PS__PARTITION_TABLE3_SEQNO(SEQNO)
go

INSERT INTO PARTITION_TABLE_SWITCH_RE
SELECT * FROM PARTITION_TABLE_SWITCH
GO

-- 되돌려 진다.
ALTER TABLE PARTITION_TABLE_SWITCH_RE SWITCH PARTITION 2 TO PARTITION_TABLE PARTITION 2 ;
GO

SELECT OBJECT_NAME(OBJECT_ID), *
FROM SYS.PARTITIONS
WHERE OBJECT_ID = OBJECT_ID('PARTITION_TABLE')
ORDER BY PARTITION_NUMBER, INDEX_ID;

--partition_id	object_id	index_id	partition_number	hobt_id	rows
--PARTITION_TABLE	72057594042777600	338100245	1	1	72057594042777600	0
--PARTITION_TABLE	72057594044612608	338100245	1	2	72057594044612608	9  --> 다시 들어온 것을 확인 할 수 있음
--PARTITION_TABLE	72057594042908672	338100245	1	3	72057594042908672	10
--PARTITION_TABLE	72057594042974208	338100245	1	4	72057594042974208	10
--PARTITION_TABLE	72057594043039744	338100245	1	5	72057594043039744	20
--PARTITION_TABLE	72057594043236352	338100245	1	6	72057594043236352	10
--PARTITION_TABLE	72057594043301888	338100245	1	7	72057594043301888	31

/* 
  인덱스만 같으면 된다. 

*/

DROP TABLE PARTITION_TABLE2

CREATE TABLE PARTITION_TABLE2
	( SEQNO  INT NOT NULL ,
	  NAME	 NVARCHAR(10) NOT NULL
    ) ON PS__PARTITION_TABLE2_SEQNO (SEQNO)

ALTER TABLE PARTITION_TABLE2  ADD CONSTRAINT PK__PARTITION_TABLE2__SEQNO
	PRIMARY KEY CLUSTERED (SEQNO) ON  PS__PARTITION_TABLE2_SEQNO (SEQNO)
GO


DECLARE @i int
SET @i = 1
WHILE (@i < = 90)
BEGIN
	INSERT PARTITION_TABLE2 (seqno, name)
	VALUES (@i, 'test' + convert(nvarchar,@i))
	SET @i = @i + 1
END

exec up_DBA_helptable_partition 'PARTITION_TABLE2'



DROP TABLE PARTITION_TABLE_SWITCH
go

CREATE TABLE PARTITION_TABLE_SWITCH
	( SEQNO  INT NOT NULL ,
	  NAME	 NVARCHAR(10) NOT NULL
    ) ON T_PARTITION_FG_04

ALTER TABLE PARTITION_TABLE_SWITCH  ADD CONSTRAINT PK__PARTITION_TABLE_SWITCH__SEQNO
	PRIMARY KEY CLUSTERED (SEQNO) ON T_PARTITION_FG_04
go

ALTER TABLE PARTITION_TABLE2 SWITCH PARTITION 2 TO PARTITION_TABLE_SWITCH ;

--메시지 4939, 수준 16, 상태 1, 줄 1
--ALTER TABLE SWITCH 문이 실패했습니다. 인덱스 'TestDB.dbo.PARTITION_TABLE_SWITCH.PK__PARTITION_TABLE_SWITCH__SEQNO'은(는) 파일 그룹 'T_PARTITION_FG_04'에 있고 인덱스 'TestDB.dbo.PARTITION_TABLE2.PK__PARTITION_TABLE2__SEQNO'의 파티션 2은(는) 파일 그룹 'T_PARTITION_FG_02'에 있습니다.

ALTER TABLE PARTITION_TABLE_SWITCH DROP CONSTRAINT PK__PARTITION_TABLE_SWITCH__SEQNO

ALTER TABLE PARTITION_TABLE_SWITCH  ADD CONSTRAINT PK__PARTITION_TABLE_SWITCH__SEQNO
	PRIMARY KEY CLUSTERED (SEQNO) ON T_PARTITION_FG_02
go

ALTER TABLE PARTITION_TABLE2 SWITCH PARTITION 2 TO PARTITION_TABLE_SWITCH ;




/*
	CASE 2
		원본에 PK 생성하고 
		대상에 PK를 만들지 않음
*/

DROP TABLE PARTITION_TABLE2

CREATE TABLE PARTITION_TABLE2
	( SEQNO  INT NOT NULL ,
	  NAME	 NVARCHAR(10) NOT NULL
    ) ON PS__PARTITION_TABLE2_SEQNO (SEQNO)

ALTER TABLE PARTITION_TABLE2  ADD CONSTRAINT PK__PARTITION_TABLE2__SEQNO
	PRIMARY KEY CLUSTERED (SEQNO) ON  PS__PARTITION_TABLE2_SEQNO (SEQNO)
GO


DECLARE @i int
SET @i = 1
WHILE (@i < = 90)
BEGIN
	INSERT PARTITION_TABLE2 (seqno, name)
	VALUES (@i, 'test' + convert(nvarchar,@i))
	SET @i = @i + 1
END


DROP TABLE PARTITION_TABLE_SWITCH
go

CREATE TABLE PARTITION_TABLE_SWITCH
	( SEQNO  INT NOT NULL ,
	  NAME	 NVARCHAR(10) NOT NULL
    ) ON T_PARTITION_FG_02


-- 파일 그룹 2번을 SWITCH
ALTER TABLE PARTITION_TABLE2 SWITCH PARTITION 2 TO PARTITION_TABLE_SWITCH ;
GO


--메시지 4913, 수준 16, 상태 1, 줄 2
--ALTER TABLE SWITCH 문이 실패했습니다. 테이블 'TestDB.dbo.PARTITION_TABLE_SWITCH'에는 클러스터형 인덱스가 없지만 테이블 'TestDB.dbo.PARTITION_TABLE2'에는 클러스터형 인덱스 'PK__PARTITION_TABLE2__SEQNO'이(가) 있습니다.

--결론) 같은 KEY 구조여야 한다.





/*
	CASE 3 
	
	파티션 테이블, PK 글로벌 KEY

*/


-- 원본은 PK가 PRIMARY 이고 switch 할 껀 파티션 되어 있음.
DROP TABLE PARTITION_TABLE2
GO

CREATE TABLE PARTITION_TABLE2
	( SEQNO  INT NOT NULL ,
	  NAME	 NVARCHAR(10) NOT NULL
    ) ON PS__PARTITION_TABLE2_SEQNO (SEQNO)

ALTER TABLE PARTITION_TABLE2  ADD CONSTRAINT PK__PARTITION_TABLE2__NAME
	PRIMARY KEY NONCLUSTERED (NAME) ON [PRIMARY]


CREATE CLUSTERED INDEX  IDX__PARTITION_TABLE2__SEQNO ON PARTITION_TABLE2
	(SEQNO) ON PS__PARTITION_TABLE2_SEQNO (SEQNO)

DECLARE @i int
SET @i = 1
WHILE (@i < = 90)
BEGIN
	INSERT PARTITION_TABLE2 (seqno, name)
	VALUES (@i, 'test' + convert(nvarchar,@i))
	SET @i = @i + 1
END

exec up_DBA_helptable_partition 'PARTITION_TABLE2'

 
-- SWITCH 할 테이블 생성
DROP TABLE PARTITION_TABLE_SWITCH
go

CREATE TABLE PARTITION_TABLE_SWITCH
	( SEQNO  INT NOT NULL ,
	  NAME	 NVARCHAR(10) NOT NULL
    ) ON T_PARTITION_FG_02

ALTER TABLE PARTITION_TABLE_SWITCH  ADD CONSTRAINT PK__PARTITION_TABLE_SWITCH__SEQNO
	PRIMARY KEY NONCLUSTERED (SEQNO) ON [PRIMARY]
go


CREATE CLUSTERED INDEX  IDX__PARTITION_TABLE_SWITCH__SEQNO ON PARTITION_TABLE_SWITCH
	(SEQNO) ON T_PARTITION_FG_02

ALTER TABLE PARTITION_TABLE2 SWITCH PARTITION 2 TO PARTITION_TABLE_SWITCH ;
GO

--메시지 7733, 수준 16, 상태 4, 줄 1
--'ALTER TABLE SWITCH' 문이 실패했습니다. 테이블 'TestDB.dbo.PARTITION_TABLE2'은(는) 분할되었고 인덱스 'PK__PARTITION_TABLE2__NAME'은(는) 분할되지 않았습니다.

-- 결론) PK나 인덱스 일부가 분할되어 있지 않고 GLOBAL 인덱스로 생성되어 있어서 SWITCH 할 수 없다는 메세지


-- 재 시도 

ALTER INDEX PK__PARTITION_TABLE2__NAME ON dbo.PARTITION_TABLE2  DISABLE;
go

SELECT * FROM SYS.SYSINDEXES WHERE ID = object_id('PARTITION_TABLE2')

-- 대상 테이블을 다시 만든다.

DROP TABLE PARTITION_TABLE_SWITCH
go

CREATE TABLE PARTITION_TABLE_SWITCH
	( SEQNO  INT NOT NULL ,
	  NAME	 NVARCHAR(10) NOT NULL
    ) ON T_PARTITION_FG_02

--ALTER TABLE PARTITION_TABLE_SWITCH  ADD CONSTRAINT PK__PARTITION_TABLE_SWITCH__SEQNO
--	PRIMARY KEY NONCLUSTERED (SEQNO) ON [PRIMARY]
--go
-- PK를 DISABLE를 했기 때문에 만들면 안된다.
--메시지 4947, 수준 16, 상태 1, 줄 1
--ALTER TABLE SWITCH 문이 실패했습니다. 원본 테이블 'TestDB.dbo.PARTITION_TABLE2'에 대상 테이블 'TestDB.dbo.PARTITION_TABLE_SWITCH'의 인덱스 'PK__PARTITION_TABLE_SWITCH__SEQNO'과(와) 같은 인덱스가 없습니다 .



CREATE CLUSTERED INDEX  IDX__PARTITION_TABLE_SWITCH__SEQNO ON PARTITION_TABLE_SWITCH
	(SEQNO) ON T_PARTITION_FG_02

ALTER TABLE PARTITION_TABLE2 SWITCH PARTITION 2 TO PARTITION_TABLE_SWITCH ;
GO

-- DISABLE 된 PK__PARTITION_TABLE2__NAME 를다시리빌드함 
ALTER INDEX PK__PARTITION_TABLE2__NAME ON [DBO]. PARTITION_TABLE2 REBUILD 
GO 

exec up_DBA_helptable_partition 'PARTITION_TABLE2'
--boundary	range	destination_id	file_group	rows
--RIGHT	NULL	1	T_PARTITION_FG_01	0
--RIGHT	10 이상 ~ 20 미만	3	T_PARTITION_FG_03	10
--RIGHT	20 이상 ~ 30 미만	4	T_PARTITION_FG_01	10
--RIGHT	30 이상 ~ 50 미만	5	T_PARTITION_FG_02	20
--RIGHT	50 이상 ~ 60 미만	6	T_PARTITION_FG_01	10
--RIGHT	60 이상 ~ 100 미만	7	T_PARTITION_FG_01	31
--RIGHT	100 이상	8	T_PARTITION_FG_03	0
--RIGHT	10 이상 ~ 10 미만	2	T_PARTITION_FG_02	0


SELECT * FROM PARTITION_TABLE_SWITCH
-- 9행


/*
	CASE 4
	
	PK CLUSTERED, 파티션 만 있는데 
	대상 테이블 파티션 되어 있음
	테이블에 PK랑 분할된 INDEX가 함께 있을 때
	
*/

DROP TABLE PARTITION_TABLE2

CREATE TABLE PARTITION_TABLE2
	( SEQNO  INT NOT NULL ,
	  NAME	 NVARCHAR(10) NOT NULL
    ) ON PS__PARTITION_TABLE2_SEQNO (SEQNO)

ALTER TABLE PARTITION_TABLE2  ADD CONSTRAINT PK__PARTITION_TABLE2__SEQNO
	PRIMARY KEY CLUSTERED (SEQNO) ON  PS__PARTITION_TABLE2_SEQNO (SEQNO)
GO




DECLARE @i int
SET @i = 1
WHILE (@i < = 90)
BEGIN
	INSERT PARTITION_TABLE2 (seqno, name)
	VALUES (@i, 'test' + convert(nvarchar,@i))
	SET @i = @i + 1
END

exec up_DBA_helptable_partition 'PARTITION_TABLE2'


-- SWITCH 할 테이블 생성
DROP TABLE PARTITION_TABLE_SWITCH
go

CREATE TABLE PARTITION_TABLE_SWITCH
	( SEQNO  INT NOT NULL ,
	  NAME	 NVARCHAR(10) NOT NULL
    ) ON T_PARTITION_FG_02

ALTER TABLE PARTITION_TABLE_SWITCH  ADD CONSTRAINT PK__PARTITION_TABLE_SWITCH__SEQNO
	PRIMARY KEY CLUSTERED (SEQNO) ON PS__PARTITION_TABLE2_SEQNO (SEQNO)
go

CREATE NONCLUSTERED INDEX  IDX__PARTITION_TABLE_SWITCH__NAME ON PARTITION_TABLE_SWITCH
	(NAME) ON PS__PARTITION_TABLE2_SEQNO (SEQNO)
GO


ALTER TABLE PARTITION_TABLE2 SWITCH PARTITION 2 TO PARTITION_TABLE_SWITCH PARTITION 2 ;
GO
--메시지 4947, 수준 16, 상태 1, 줄 1
--ALTER TABLE SWITCH 문이 실패했습니다. 원본 테이블 'TestDB.dbo.PARTITION_TABLE2'에 대상 테이블 'TestDB.dbo.PARTITION_TABLE_SWITCH'의 인덱스 'IDX__PARTITION_TABLE_SWITCH__NAME'과(와) 같은 인덱스가 없습니다 .


-- 원본에 인덱스를 만들고 함.
CREATE NONCLUSTERED INDEX  IDX__PARTITION_TABLE2__NAME ON PARTITION_TABLE2
	(NAME) ON PS__PARTITION_TABLE2_SEQNO (SEQNO)
GO

ALTER TABLE PARTITION_TABLE2 SWITCH PARTITION 2 TO PARTITION_TABLE_SWITCH PARTITION 2 ;
GO

exec up_DBA_helptable_partition 'PARTITION_TABLE2'
exec up_DBA_helptable_partition 'PARTITION_TABLE_SWITCH'



/* =========기타 에러 

1. 테이블 컬럼 형식이 다를 경우
메시지 4985, 수준 16, 상태 1, 줄 1
테이블 'TestDB.dbo.PARTITION_TABLE2'과(와) 'TestDB.dbo.PARTITION_TABLE_SWITCH'에서의 열 'NAME'의 Null 허용 여부 특성이 다르므로 ALTER TABLE SWITCH 문이 실패했습니다.

