--==================================
--  통계 사항 보기
--==================================
SET STATISTICS IO ON;SET STATISTICS TIME ON;SET STATISTICS PROFILE ON
GO

SET STATISTICS IO OFF;SET STATISTICS TIME OFF;SET STATISTICS PROFILE OFF
GO


SET SHOWPLAN_ALL ON
SET SHOWPLAN_TEXT ON
GO

SET SHOWPLAN_ALL OFF
SET SHOWPLAN_TEXT OFF
GO



-- COST 조정 , 2000만 가능하고 2005에서는 sp_configure로 변경해야 함.
SET QUERY_GOVERNOR_COST_LIMIT 200