-- =========================
--  사용되지 않은 Index
-- =========================

-- SQL 2000용
SELECT  USER_NAME( OBJECTPROPERTY( I.ID, 'DBOWR_WORK' ) ) AS OWNER
   ,OBJECT_NAME( I.ID ) AS [TABLE]
   , I.NAME AS [INDEX]
   ,CASE INDEXPROPERTY( I.ID , I.NAME , 'ISCLUSTERED')  WHEN 1 THEN 'Y'  ELSE ''   END AS ISCLUSTERED
   ,CASE INDEXPROPERTY( I.ID , I.NAME , 'ISUNIQUE'    )  WHEN 1 THEN 'Y'  ELSE ''   END AS ISUNIQUE
   ,STATS_DATE( I.ID , I.INDID ) AS LASTUPDATEDDATE
   ,DPAGES * 8. /1024 AS MB
FROM SYSINDEXES AS I
WHERE OBJECTPROPERTY( I.ID, 'ISMSSHIPPED' ) = 0 
 AND 1 NOT IN ( INDEXPROPERTY( I.ID , I.NAME , 'ISSTATISTICS'   ) 
  , INDEXPROPERTY( I.ID , I.NAME , 'ISAUTOSTATISTICS' ) 
  , INDEXPROPERTY( I.ID , I.NAME , 'ISHYPOTHETICAL'   )  )
 AND I.INDID BETWEEN 1 AND 250
-- AND DPAGES > 100 --작은 크기 테이블 무시
 AND (STATS_DATE( I.ID , I.INDID ) < GETDATE() - 15 
  OR STATS_DATE( I.ID , I.INDID ) IS NULL) --15일 이전까지도 업데이트 안된 것
ORDER BY OWNER, [TABLE], [INDEX]
GO
