--211.115.74.109 메인 
USE TIGER
GO

REVOKE INSERT ON OBJECT::SMSMSG FROM dev;
GO
REVOKE UPDATE ON OBJECT::DELIVERY_FEE_PAYMENT FROM dev;
GO

USE EVENT
GO

REVOKE INSERT ON OBJECT::dcoupon_statistics FROM dev;
GO
REVOKE UPDATE ON OBJECT::dcoupon_statistics FROM dev;
GO
REVOKE INSERT ON OBJECT::gift_event_daily_statistics FROM dev;
GO
REVOKE UPDATE ON OBJECT::gift_event_daily_statistics FROM dev;
GO
REVOKE DELETE ON OBJECT::DCOUPON_GOODS FROM dev;
GO
REVOKE INSERT ON OBJECT::DCOUPON_GOODS FROM dev;
GO
REVOKE UPDATE ON OBJECT::DCOUPON_MASTER FROM dev;
GO
REVOKE DELETE ON OBJECT::DLOT_DETAIL FROM dev;
GO
REVOKE UPDATE ON OBJECT::DLOT_DETAIL FROM dev;
GO
REVOKE UPDATE ON OBJECT::EVENT FROM dev;
GO
REVOKE INSERT ON OBJECT::gift_event_winner_common FROM dev;
GO
REVOKE UPDATE ON OBJECT::gift_event_winner_common FROM dev;
GO

USE SETTLE
GO

REVOKE INSERT ON OBJECT::sttl_custom_balance FROM dev;
GO
REVOKE UPDATE ON OBJECT::sttl_custom_balance FROM dev;
GO
REVOKE INSERT ON OBJECT::STTL_RETURN FROM dev;
GO
REVOKE INSERT ON OBJECT::STTL_OUTSTANDING_DIV FROM dev;
GO
REVOKE UPDATE ON OBJECT::STTL_OUTSTANDING_DIV FROM dev;
GO
REVOKE UPDATE ON OBJECT::STTL_SELLER_OUTPUT_BANK_INFO FROM dev;
GO
REVOKE UPDATE ON OBJECT::STTL_TRANS_FEE_SETTLE FROM dev;
GO
REVOKE DELETE ON OBJECT::STTL_DEFER_CON_CASH FROM dev;
GO
REVOKE INSERT ON OBJECT::STTL_DEFER_CON_CASH FROM dev;
GO
REVOKE UPDATE ON OBJECT::STTL_DEFER_CON_CASH FROM dev;
GO
REVOKE DELETE ON OBJECT::STTL_PREPAY FROM dev;
GO
REVOKE INSERT ON OBJECT::STTL_PREPAY FROM dev;
GO
REVOKE UPDATE ON OBJECT::STTL_PREPAY FROM dev;
GO
REVOKE UPDATE ON OBJECT::STTL_CREDIT_DIV FROM dev;
GO
REVOKE UPDATE ON OBJECT::STTL_CREDIT FROM dev;
GO
REVOKE UPDATE ON OBJECT::STTL_OUTSTANDING FROM dev;
GO

USE LION
GO

REVOKE DELETE ON OBJECT::SEARCH_INFO_NEW_DIRECT_INSERT FROM dev;
GO
REVOKE INSERT ON OBJECT::SEARCH_INFO_NEW_DIRECT_INSERT FROM dev;
GO
REVOKE UPDATE ON OBJECT::SEARCH_INFO_NEW_DIRECT_INSERT FROM dev;
GO
REVOKE UPDATE ON OBJECT::SEARCH_INFO_NEW FROM dev;
GO
REVOKE INSERT ON OBJECT::sttl_outstanding_batch FROM dev;
GO
REVOKE INSERT ON OBJECT::CHECK_SELLER_ACCOUNT FROM dev;
GO
REVOKE DELETE ON OBJECT::DSI_INSTANCE_IDENTITY FROM dev;
GO
REVOKE INSERT ON OBJECT::DSI_INSTANCE_IDENTITY FROM dev;
GO
REVOKE UPDATE ON OBJECT::DSI_INSTANCE_IDENTITY FROM dev;
GO
REVOKE DELETE ON OBJECT::DSI_CUSTOMER_CONTR_NO FROM dev;
GO
REVOKE INSERT ON OBJECT::DSI_CUSTOMER_CONTR_NO FROM dev;
GO
REVOKE UPDATE ON OBJECT::DSI_CUSTOMER_CONTR_NO FROM dev;
GO
REVOKE INSERT ON OBJECT::log_job_timeline FROM dev;
GO
REVOKE DELETE ON OBJECT::DSI_IM_TRANS_RSLT_S70 FROM dev;
GO
REVOKE INSERT ON OBJECT::DSI_IM_TRANS_RSLT_S70 FROM dev;
GO
REVOKE UPDATE ON OBJECT::DSI_IM_TRANS_RSLT_S70 FROM dev;
GO
REVOKE DELETE ON OBJECT::DSI_INVOICE_TRANS_FEE_TBL FROM dev;
GO
REVOKE INSERT ON OBJECT::DSI_INVOICE_TRANS_FEE_TBL FROM dev;
GO
REVOKE UPDATE ON OBJECT::DSI_INVOICE_TRANS_FEE_TBL FROM dev;
GO
REVOKE DELETE ON OBJECT::JT_EX_TRANS_WORK FROM dev;
GO
REVOKE INSERT ON OBJECT::JT_EX_TRANS_WORK FROM dev;
GO
REVOKE UPDATE ON OBJECT::JT_EX_TRANS_WORK FROM dev;
GO
REVOKE INSERT ON OBJECT::transport_ordersppl_cash_work FROM dev;
GO
REVOKE UPDATE ON OBJECT::transport_ordersppl_cash_work FROM dev;
GO

--121.254.218.214 정산DB
USE ACCTCLOSE
GO 

REVOKE UPDATE ON OBJECT::CUSTOM_CONVERT FROM dev;
GO
REVOKE DELETE ON OBJECT::TRADE_TRANS_DAILY FROM dev;
GO
REVOKE UPDATE ON OBJECT::TRADE_TRANS_DAILY FROM dev;
GO
REVOKE DELETE ON OBJECT::CO_COMM_DAILY FROM dev;
GO
REVOKE UPDATE ON OBJECT::DELIVERY_FEE_DAILY FROM dev;
GO
REVOKE DELETE ON OBJECT::DZ_SLIP_PROC_LOG FROM dev;
GO
REVOKE DELETE ON OBJECT::TRADE_DAILY FROM dev;
GO
REVOKE UPDATE ON OBJECT::TRADE_DAILY FROM dev;
GO
REVOKE INSERT ON OBJECT::GOODS_DR FROM dev;
GO
REVOKE UPDATE ON OBJECT::STTL_MONTHLY_VAT_DETAIL FROM dev;
GO
REVOKE UPDATE ON OBJECT::FIN_COMMISSION_TBL_NEW FROM dev;
GO
REVOKE UPDATE ON OBJECT::TRADE_TYPE_SUM FROM dev;
GO
REVOKE UPDATE ON OBJECT::CUSTOM_DR FROM dev;
GO
REVOKE UPDATE ON OBJECT::STTL_MONTHLY_VAT FROM dev;
GO
REVOKE DELETE ON OBJECT::STTL_COLLECTION FROM dev;
GO
REVOKE INSERT ON OBJECT::STTL_COLLECTION FROM dev;
GO
REVOKE UPDATE ON OBJECT::STTL_COLLECTION FROM dev;
GO
REVOKE UPDATE ON OBJECT::TRADE_SELLER_SUM FROM dev;
GO

USE DSS
GO

REVOKE INSERT ON OBJECT::BRAND_CODE FROM dev;
GO

USE PASTACCT
GO

REVOKE DELETE ON OBJECT::TRADE_DAILY_PAST FROM dev;
GO
REVOKE INSERT ON OBJECT::TRADE_DAILY_PAST FROM dev;
GO
REVOKE UPDATE ON OBJECT::TRADE_DAILY_PAST FROM dev;
GO
REVOKE UPDATE ON OBJECT::GSM_SELL_INFO_DAILY_PAST FROM dev;
GO
REVOKE INSERT ON OBJECT::DELIVERY_FEE_DAILY_PAST FROM dev;
GO
REVOKE UPDATE ON OBJECT::DELIVERY_FEE_DAILY_PAST FROM dev;
GO
REVOKE INSERT ON OBJECT::SELLER_CHARGE_DAILY_PAST FROM dev;
GO
REVOKE DELETE ON OBJECT::CO_COMM_DAILY_PAST FROM dev;
GO
REVOKE UPDATE ON OBJECT::CO_COMM_DAILY_PAST FROM dev;
GO
REVOKE INSERT ON OBJECT::COST_PRICE_DAILY_PAST FROM dev;
GO
REVOKE DELETE ON OBJECT::TRADE_TRANS_DAILY_PAST FROM dev;
GO
REVOKE INSERT ON OBJECT::TRADE_TRANS_DAILY_PAST FROM dev;
GO
REVOKE UPDATE ON OBJECT::TRADE_TRANS_DAILY_PAST FROM dev;
GO

USE WORKLOG
GO

REVOKE INSERT ON OBJECT::WORK_TRADE_SELLER_SUM_DELIVERY_FEE FROM dev;
GO
REVOKE UPDATE ON OBJECT::WORK_TRADE_SELLER_SUM_DELIVERY_FEE FROM dev;
GO
REVOKE INSERT ON OBJECT::WORK_TRADE_CARD_SELLER_SUM_DELIVERY_FEE FROM dev;
GO
REVOKE UPDATE ON OBJECT::WORK_TRADE_CARD_SELLER_SUM_DELIVERY_FEE FROM dev;
GO
REVOKE INSERT ON OBJECT::WORK_TRADE_SELLER_SUM_BUY_OFF FROM dev;
GO
REVOKE UPDATE ON OBJECT::WORK_TRADE_SELLER_SUM_BUY_OFF FROM dev;
GO
REVOKE INSERT ON OBJECT::WORK_TRADE_CARD_SELLER_SUM_BUY_OFF FROM dev;
GO
REVOKE UPDATE ON OBJECT::WORK_TRADE_CARD_SELLER_SUM_BUY_OFF FROM dev;
GO
REVOKE INSERT ON OBJECT::WORK_TRADE_TRANS_DAILY FROM dev;
GO
REVOKE UPDATE ON OBJECT::WORK_TRADE_TRANS_DAILY FROM dev;
GO
REVOKE INSERT ON OBJECT::WORK_TRADE_CARD_SELLER_SUM FROM dev;
GO
REVOKE UPDATE ON OBJECT::WORK_TRADE_CARD_SELLER_SUM FROM dev;
GO
REVOKE INSERT ON OBJECT::WORK_TRADE_DAILY FROM dev;
GO
REVOKE UPDATE ON OBJECT::WORK_TRADE_DAILY FROM dev;
GO
REVOKE INSERT ON OBJECT::WORK_UNPAIDMONEYH FROM dev;
GO
REVOKE UPDATE ON OBJECT::WORK_UNPAIDMONEYH FROM dev;
GO
REVOKE UPDATE ON OBJECT::WORKING_AP_DATE FROM dev;
GO
REVOKE INSERT ON OBJECT::WORK_TRADE_SELLER_SUM FROM dev;
GO
REVOKE UPDATE ON OBJECT::WORK_TRADE_SELLER_SUM FROM dev;
GO

USE TAX
GO 

REVOKE DELETE ON OBJECT::INVOICE_TBL FROM dev;
GO
REVOKE INSERT ON OBJECT::INVOICE_TBL FROM dev;
GO
REVOKE UPDATE ON OBJECT::INVOICE_TBL FROM dev;
GO
REVOKE INSERT ON OBJECT::INVPROCESS_TBL FROM dev;
GO
REVOKE UPDATE ON OBJECT::INVPROCESS_TBL FROM dev;
GO
REVOKE DELETE ON OBJECT::X_INVOICE_TBL FROM dev;
GO
REVOKE INSERT ON OBJECT::X_INVOICE_TBL FROM dev;
GO
REVOKE UPDATE ON OBJECT::X_INVOICE_TBL FROM dev;
GO
REVOKE DELETE ON OBJECT::BASEINVOICE_TBL FROM dev;
GO
REVOKE INSERT ON OBJECT::BASEINVOICE_TBL FROM dev;
GO
REVOKE UPDATE ON OBJECT::BASEINVOICE_TBL FROM dev;
GO
