
--윈도우 로그인생성 GMARKETSEO
CREATE LOGIN [GMARKETSEO\DBA] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[한국어];
CREATE LOGIN [GMARKETSEO\DB_MANAGER] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[한국어];
CREATE LOGIN [GMARKETSEO\DB_OP] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[한국어];
CREATE LOGIN [GMARKETSEO\DEV] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[한국어];

--윈도우 로그인생성 GMARKETINT
CREATE LOGIN [GMARKETINT\DBA] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[한국어];
CREATE LOGIN [GMARKETINT\DB_MANAGER] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[한국어];
CREATE LOGIN [GMARKETINT\DB_OP] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[한국어];
CREATE LOGIN [GMARKETINT\DEV] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[한국어];

--윈도우 로그인생성 GMARKETSEONH
CREATE LOGIN [GMARKETNH\DBA] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[한국어];
CREATE LOGIN [GMARKETNH\DB_MANAGER] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[한국어];
CREATE LOGIN [GMARKETNH\DB_OP] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[한국어];
CREATE LOGIN [GMARKETNH\DEV] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[한국어];


/******* 서버 롤 ***********/
--권한부여 ex)GMARKETNH\DB_MANAGER에게 execute, showplan, view definition 권한 부여
use [master]
GO
GRANT VIEW SERVER STATE TO [GMARKETNH\DB_MANAGER]

-- [GMARKET*/DBA] sysadmin 서버롤 부여
EXEC sys.sp_addsrvrolemember @loginame = N'GMARKETSEO\DBA', @rolename = N'sysadmin'
GO


--서버롤 확인
--EXEC sp_helpsrvrolemember
GO


-- User생성및 DB롤 부여 ex) GMARKETSEO\DEV

USE [사용자 DB] -- master해야함. 
/****** 예외 , OP 에는 master에 권한 주지 말아야함 **********/
GO

CREATE USER [GMARKETSEO\DB_MANAGER] FOR LOGIN [GMARKETSEO\DB_MANAGER]
GO
EXEC sp_addrolemember N'db_datareader', N'GMARKETSEO\DB_MANAGER'
EXEC sp_addrolemember N'db_datawriter', N'GMARKETSEO\DB_MANAGER'
if db_name() != master
begin
        EXEC sp_addrolemember N'db_ddladmin', N'GMARKETNH\DB_MANAGER' -- master에는 ddl admin 넣지 않음
end
GO


GRANT VIEW DEFINITION TO [GMARKETNH\DB_MANAGER]
GRANT SHOWPLAN TO [GMARKETNH\DB_MANAGER]
GO

if db_name() != master
begin
    CREATE USER [GMARKETSEO\DB_OP] FOR LOGIN [GMARKETSEO\DB_OP]
    GO
    EXEC sp_addrolemember N'db_datareader', N'GMARKETSEO\DB_OP'
    
    
    CREATE USER [GMARKETSEO\DEV] FOR LOGIN [GMARKETSEO\DEV]
    GO
    EXEC sp_addrolemember N'db_datareader', N'GMARKETSEO\DEV'
    EXEC sp_addrolemember N'db_ddladmin', N'GMARKETSEO\DEV'
    EXEC sp_addrolemember N'db_securityadmin', N'GMARKETSEO\DEV'
end

