/*************************************************************************  
* 프로시저명: DBO.[UP_MON_COLLECT_QUERY_STAT_ALL_PLAN]
* 작성정보	: 2016-12-15 BY CHOI BO RA
* 관련페이지:  
* 내용		:  
* 수정정보	: DB_MON_QUERY_STATS_ALL 에 해당 하는 전체 paln 정보 저장, 2014 upgrade시 필요

**************************************************************************/
CREATE PROCEDURE [DBO].[UP_MON_COLLECT_QUERY_STAT_ALL_PLAN]        
AS        
SET NOCOUNT ON        
SET QUERY_GOVERNOR_COST_LIMIT 0        
DECLARE @REG_DATE DATETIME   



SELECT TOP 1 @REG_DATE  = REG_DATE FROM DB_MON_QUERY_STATS_ALL WITH(NOLOCK) ORDER BY REG_DATE DESC


DELETE DB_MON_QUERY_STATS_ALL_PLAN
FROM DBO.DB_MON_QUERY_STATS_ALL_PLAN AS PL
 JOIN (SELECT @REG_DATE AS REG_DATE, ST.PLAN_HANDLE, ST.STATEMENT_START_OFFSET, ST.STATEMENT_END_OFFSET
			, ST.CREATION_TIME, DB_NAME(PS.DBID) AS DB_NAME, PS.QUERY_PLAN
		FROM DB_MON_QUERY_STATS_ALL AS ST WITH(NOLOCK) 
		   CROSS APPLY SYS.DM_EXEC_TEXT_QUERY_PLAN(ST.PLAN_HANDLE, ST.STATEMENT_START_OFFSET, ST.STATEMENT_END_OFFSET) AS PS
		WHERE  ST.REG_DATE =@REG_DATE
		) AS NEW_PL  ON PL.PLAN_HANDLE = NEW_PL.PLAN_HANDLE  AND PL.STATEMENT_START = NEW_PL.STATEMENT_START_OFFSET AND PL.STATEMENT_END = NEW_PL.STATEMENT_END_OFFSET   AND PL.CREATION_TIME != NEW_PL.CREATION_TIME


INSERT INTO DBO.DB_MON_QUERY_STATS_ALL_PLAN
( REG_DATE
,PLAN_HANDLE
,STATEMENT_START
,STATEMENT_END
,CREATION_TIME
,DB_NAME
,QUERY_PLAN
)
SELECT NEW_PL.*
FROM DBO.DB_MON_QUERY_STATS_ALL_PLAN AS PL
RIGHT JOIN (SELECT @REG_DATE AS REG_DATE, ST.PLAN_HANDLE, ST.STATEMENT_START_OFFSET, ST.STATEMENT_END_OFFSET
			, ST.CREATION_TIME, DB_NAME(PS.DBID) AS DB_NAME, PS.QUERY_PLAN
			FROM DB_MON_QUERY_STATS_ALL AS ST WITH(NOLOCK) 
			   CROSS APPLY SYS.DM_EXEC_TEXT_QUERY_PLAN(ST.PLAN_HANDLE, ST.STATEMENT_START_OFFSET, ST.STATEMENT_END_OFFSET) AS PS
			WHERE  ST.REG_DATE =@REG_DATE
			) AS NEW_PL  ON PL.PLAN_HANDLE = NEW_PL.PLAN_HANDLE  AND PL.STATEMENT_START = NEW_PL.STATEMENT_START_OFFSET AND PL.STATEMENT_END = NEW_PL.STATEMENT_END_OFFSET

WHERE PL.QUERY_PLAN IS NULL
go


/*************************************************************************  
* 프로시저명: DBO.[UP_MON_COLLECT_QUERY_STAT_ALL_PLAN_DELETE]
* 작성정보	: 2016-12-15 BY CHOI BO RA
* 관련페이지:  
* 내용		:  
* 수정정보	: DB_MON_QUERY_STATS_ALL_PLAN 40일 보전 삭제

**************************************************************************/
CREATE PROCEDURE [DBO].[UP_MON_COLLECT_QUERY_STAT_ALL_PLAN_DELETE]        
AS        
SET NOCOUNT ON        
SET QUERY_GOVERNOR_COST_LIMIT 0        
DECLARE @REG_DATE DATETIME   



DELETE DB_MON_QUERY_STATS_ALL_PLAN  WHERE REG_DATE <= DATEADD(DD, -40, GETDATE())

